package com.vlt.zeroperte.ui.theme
import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext

@Immutable
data class ExtendedColorScheme(
    val expiredCard: ColorFamily,
    val expiredSoonCard: ColorFamily,
    val validCard: ColorFamily,
    val expiredCardTypo: ColorFamily,
    val expiredSoonCardTypo: ColorFamily,
    val validCardTypo: ColorFamily,
)

private val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

val extendedLight = ExtendedColorScheme(
  expiredCard = ColorFamily(
      expiredCardLight,
      onExpiredCardLight,
      expiredCardContainerLight,
      onExpiredCardContainerLight,
      expiredCardTypoLight,
      onExpiredCardTypoLight,
      expiredCardTypoContainerLight,
      onExpiredCardTypoContainerLight,
  ),
  expiredSoonCard = ColorFamily(
      expiredSoonCardLight,
      onExpiredSoonCardLight,
      expiredSoonCardContainerLight,
      onExpiredSoonCardContainerLight,
      expiredSoonCardTypoLight,
      onExpiredSoonCardTypoLight,
      expiredSoonCardTypoContainerLight,
      onExpiredSoonCardTypoContainerLight,
  ),
  validCard = ColorFamily(
      validCardLight,
      onValidCardLight,
      validCardContainerLight,
      onValidCardContainerLight,
      validCardTypoLight,
      onValidCardTypoLight,
      validCardTypoContainerLight,
      onValidCardTypoContainerLight,
  ),
  expiredCardTypo = ColorFamily(
      expiredCardTypoLight,
      onExpiredCardTypoLight,
      expiredCardTypoContainerLight,
      onExpiredCardTypoContainerLight,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  expiredSoonCardTypo = ColorFamily(
      expiredSoonCardTypoLight,
      onExpiredSoonCardTypoLight,
      expiredSoonCardTypoContainerLight,
      onExpiredSoonCardTypoContainerLight,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  validCardTypo = ColorFamily(
      validCardTypoLight,
      onValidCardTypoLight,
      validCardTypoContainerLight,
      onValidCardTypoContainerLight,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
)

val extendedDark = ExtendedColorScheme(
  expiredCard = ColorFamily(
      expiredCardDark,
      onExpiredCardDark,
      expiredCardContainerDark,
      onExpiredCardContainerDark,
      expiredCardTypoDark,
      onExpiredCardTypoDark,
      expiredCardTypoContainerDark,
      onExpiredCardTypoContainerDark,
  ),
  expiredSoonCard = ColorFamily(
      expiredSoonCardDark,
      onExpiredSoonCardDark,
      expiredSoonCardContainerDark,
      onExpiredSoonCardContainerDark,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  validCard = ColorFamily(
      validCardDark,
      onValidCardDark,
      validCardContainerDark,
      onValidCardContainerDark,
      validCardTypoDark,
      onValidCardTypoDark,
      validCardTypoContainerDark,
      onValidCardTypoContainerDark,
  ),
  expiredCardTypo = ColorFamily(
      expiredCardTypoDark,
      onExpiredCardTypoDark,
      expiredCardTypoContainerDark,
      onExpiredCardTypoContainerDark,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  expiredSoonCardTypo = ColorFamily(
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  validCardTypo = ColorFamily(
      validCardTypoDark,
      onValidCardTypoDark,
      validCardTypoContainerDark,
      onValidCardTypoContainerDark,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
)

val extendedLightMediumContrast = ExtendedColorScheme(
  expiredCard = ColorFamily(
      expiredCardLightMediumContrast,
      onExpiredCardLightMediumContrast,
      expiredCardContainerLightMediumContrast,
      onExpiredCardContainerLightMediumContrast,
      expiredCardTypoLightMediumContrast,
      onExpiredCardTypoLightMediumContrast,
      expiredCardTypoContainerLightMediumContrast,
      onExpiredCardTypoContainerLightMediumContrast,
  ),
  expiredSoonCard = ColorFamily(
      expiredSoonCardLightMediumContrast,
      onExpiredSoonCardLightMediumContrast,
      expiredSoonCardContainerLightMediumContrast,
      onExpiredSoonCardContainerLightMediumContrast,
      expiredSoonCardTypoLightMediumContrast,
      onExpiredSoonCardTypoLightMediumContrast,
      expiredSoonCardTypoContainerLightMediumContrast,
      onExpiredSoonCardTypoContainerLightMediumContrast,
  ),
  validCard = ColorFamily(
      validCardLightMediumContrast,
      onValidCardLightMediumContrast,
      validCardContainerLightMediumContrast,
      onValidCardContainerLightMediumContrast,
      validCardTypoLightMediumContrast,
      onValidCardTypoLightMediumContrast,
      validCardTypoContainerLightMediumContrast,
      onValidCardTypoContainerLightMediumContrast,
  ),
  expiredCardTypo = ColorFamily(
      expiredCardTypoLightMediumContrast,
      onExpiredCardTypoLightMediumContrast,
      expiredCardTypoContainerLightMediumContrast,
      onExpiredCardTypoContainerLightMediumContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  expiredSoonCardTypo = ColorFamily(
      expiredSoonCardTypoLightMediumContrast,
      onExpiredSoonCardTypoLightMediumContrast,
      expiredSoonCardTypoContainerLightMediumContrast,
      onExpiredSoonCardTypoContainerLightMediumContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  validCardTypo = ColorFamily(
      validCardTypoLightMediumContrast,
      onValidCardTypoLightMediumContrast,
      validCardTypoContainerLightMediumContrast,
      onValidCardTypoContainerLightMediumContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
)

val extendedLightHighContrast = ExtendedColorScheme(
  expiredCard = ColorFamily(
      expiredCardLightHighContrast,
      onExpiredCardLightHighContrast,
      expiredCardContainerLightHighContrast,
      onExpiredCardContainerLightHighContrast,
      expiredCardTypoLightHighContrast,
      onExpiredCardTypoLightHighContrast,
      expiredCardTypoContainerLightHighContrast,
      onExpiredCardTypoContainerLightHighContrast,
  ),
  expiredSoonCard = ColorFamily(
      expiredSoonCardLightHighContrast,
      onExpiredSoonCardLightHighContrast,
      expiredSoonCardContainerLightHighContrast,
      onExpiredSoonCardContainerLightHighContrast,
      expiredSoonCardTypoLightHighContrast,
      onExpiredSoonCardTypoLightHighContrast,
      expiredSoonCardTypoContainerLightHighContrast,
      onExpiredSoonCardTypoContainerLightHighContrast,
  ),
  validCard = ColorFamily(
      validCardLightHighContrast,
      onValidCardLightHighContrast,
      validCardContainerLightHighContrast,
      onValidCardContainerLightHighContrast,
      validCardTypoLightHighContrast,
      onValidCardTypoLightHighContrast,
      validCardTypoContainerLightHighContrast,
      onValidCardTypoContainerLightHighContrast,
  ),
  expiredCardTypo = ColorFamily(
      expiredCardTypoLightHighContrast,
      onExpiredCardTypoLightHighContrast,
      expiredCardTypoContainerLightHighContrast,
      onExpiredCardTypoContainerLightHighContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  expiredSoonCardTypo = ColorFamily(
      expiredSoonCardTypoLightHighContrast,
      onExpiredSoonCardTypoLightHighContrast,
      expiredSoonCardTypoContainerLightHighContrast,
      onExpiredSoonCardTypoContainerLightHighContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  validCardTypo = ColorFamily(
      validCardTypoLightHighContrast,
      onValidCardTypoLightHighContrast,
      validCardTypoContainerLightHighContrast,
      onValidCardTypoContainerLightHighContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
)

val extendedDarkMediumContrast = ExtendedColorScheme(
  expiredCard = ColorFamily(
      expiredCardDarkMediumContrast,
      onExpiredCardDarkMediumContrast,
      expiredCardContainerDarkMediumContrast,
      onExpiredCardContainerDarkMediumContrast,
      expiredCardTypoDarkMediumContrast,
      onExpiredCardTypoDarkMediumContrast,
      expiredCardTypoContainerDarkMediumContrast,
      onExpiredCardTypoContainerDarkMediumContrast,
  ),
  expiredSoonCard = ColorFamily(
      expiredSoonCardDarkMediumContrast,
      onExpiredSoonCardDarkMediumContrast,
      expiredSoonCardContainerDarkMediumContrast,
      onExpiredSoonCardContainerDarkMediumContrast,
      expiredSoonCardTypoDarkMediumContrast,
      onExpiredSoonCardTypoDarkMediumContrast,
      expiredSoonCardTypoContainerDarkMediumContrast,
      onExpiredSoonCardTypoContainerDarkMediumContrast,
  ),
  validCard = ColorFamily(
      validCardDarkMediumContrast,
      onValidCardDarkMediumContrast,
      validCardContainerDarkMediumContrast,
      onValidCardContainerDarkMediumContrast,
      validCardTypoDarkMediumContrast,
      onValidCardTypoDarkMediumContrast,
      validCardTypoContainerDarkMediumContrast,
      onValidCardTypoContainerDarkMediumContrast,
  ),
  expiredCardTypo = ColorFamily(
      expiredCardTypoDarkMediumContrast,
      onExpiredCardTypoDarkMediumContrast,
      expiredCardTypoContainerDarkMediumContrast,
      onExpiredCardTypoContainerDarkMediumContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  expiredSoonCardTypo = ColorFamily(
      expiredSoonCardTypoDarkMediumContrast,
      onExpiredSoonCardTypoDarkMediumContrast,
      expiredSoonCardTypoContainerDarkMediumContrast,
      onExpiredSoonCardTypoContainerDarkMediumContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  validCardTypo = ColorFamily(
      validCardTypoDarkMediumContrast,
      onValidCardTypoDarkMediumContrast,
      validCardTypoContainerDarkMediumContrast,
      onValidCardTypoContainerDarkMediumContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
)

val extendedDarkHighContrast = ExtendedColorScheme(
  expiredCard = ColorFamily(
      expiredCardDarkHighContrast,
      onExpiredCardDarkHighContrast,
      expiredCardContainerDarkHighContrast,
      onExpiredCardContainerDarkHighContrast,
      expiredCardTypoDarkHighContrast,
      onExpiredCardTypoDarkHighContrast,
      expiredCardTypoContainerDarkHighContrast,
      onExpiredCardTypoContainerDarkHighContrast,
  ),
  expiredSoonCard = ColorFamily(
      expiredSoonCardDarkHighContrast,
      onExpiredSoonCardDarkHighContrast,
      expiredSoonCardContainerDarkHighContrast,
      onExpiredSoonCardContainerDarkHighContrast,
      expiredSoonCardTypoDarkHighContrast,
      onExpiredSoonCardTypoDarkHighContrast,
      expiredSoonCardTypoContainerDarkHighContrast,
      onExpiredSoonCardTypoContainerDarkHighContrast,
  ),
  validCard = ColorFamily(
      validCardDarkHighContrast,
      onValidCardDarkHighContrast,
      validCardContainerDarkHighContrast,
      onValidCardContainerDarkHighContrast,
      validCardTypoDarkHighContrast,
      onValidCardTypoDarkHighContrast,
      validCardTypoContainerDarkHighContrast,
      onValidCardTypoContainerDarkHighContrast,
  ),
  expiredCardTypo = ColorFamily(
      expiredCardTypoDarkHighContrast,
      onExpiredCardTypoDarkHighContrast,
      expiredCardTypoContainerDarkHighContrast,
      onExpiredCardTypoContainerDarkHighContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  expiredSoonCardTypo = ColorFamily(
      expiredSoonCardTypoDarkHighContrast,
      onExpiredSoonCardTypoDarkHighContrast,
      expiredSoonCardTypoContainerDarkHighContrast,
      onExpiredSoonCardTypoContainerDarkHighContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
  validCardTypo = ColorFamily(
      validCardTypoDarkHighContrast,
      onValidCardTypoDarkHighContrast,
      validCardTypoContainerDarkHighContrast,
      onValidCardTypoContainerDarkHighContrast,
      expiredSoonCardTypoDark,
      onExpiredSoonCardTypoDark,
      expiredSoonCardTypoContainerDark,
      onExpiredSoonCardTypoContainerDark,
  ),
)

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color,
    val expiredSoonCardTypoDark1: Color,
    val onExpiredSoonCardTypoDark1: Color,
    val expiredSoonCardTypoContainerDark1: Color,
    val onExpiredSoonCardTypoContainerDark1: Color
)

val unspecified_scheme = ColorFamily(
    Color.Unspecified,
    Color.Unspecified,
    Color.Unspecified,
    Color.Unspecified,
    expiredSoonCardTypoDark,
    onExpiredSoonCardTypoDark,
    expiredSoonCardTypoContainerDark,
    onExpiredSoonCardTypoContainerDark
)

@Composable
fun ZeroPerteTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    // Dynamic color is available on Android 12+
    dynamicColor: Boolean = true,
    content: @Composable() () -> Unit
) {
  val colorScheme = when {
      dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
          val context = LocalContext.current
          if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
      }
      
      darkTheme -> darkScheme
      else -> lightScheme
  }

  MaterialTheme(
    colorScheme = colorScheme,
    typography = AppTypography,
    content = content
  )
}

