ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.zeroperte.HttpKt.configureHttp
      - com.zeroperte.SerializationKt.configureSerialization
      - com.zeroperte.StatusPagesKt.configureStatusPages
      - com.zeroperte.KoinKt.configureKoin
      - com.zeroperte.ExposedKt.configureExposed
      - com.zeroperte.RoutingKt.configureRouting
